dist: trusty
language: java
jdk:
       - openjdk8
       - openjdk11
       - openjdk-ea
       - oraclejdk8
       - oraclejdk11
       - oraclejdk-ea
sudo: false
script: mvn clean verify

deploy:
api_key:
secure: "3RhyhGHITKycyCL-ZjGeGg"
install:
       - pip install selenium
       - pip install requests

notifications:
       email: la.crymosa321@gmail.com